import json
import os
import requests
from typing import Any, Dict

OLLAMA_API_URL: str = os.getenv("OLLAMA_API_URL", "http://localhost:11434/api/chat")
MODEL_NAME: str = os.getenv("OLLAMA_MODEL", "llama3.2")

SYSTEM_PROMPT: str = (
    "You are HireFlow AI, an expert HR Recruiter, Senior Technical Interviewer, "
    "Behavioral Psychologist, Executive Communication Coach, and AI Interview Evaluator.\n\n"
    "Your task is to analyze interview telemetry generated by an AI Interview System.\n"
    "The telemetry contains objective computer vision measurements and Python pre-calculated performance labels.\n\n"
    "STRICT SYSTEM RULES:\n"
    "1. Use ONLY the performance levels provided in 'performance_classifications' (e.g., Excellent, Good, Average, Needs Improvement, Not Ready).\n"
    "2. Do NOT invent, override, or change any pre-calculated performance labels or score numbers.\n"
    "3. Your task is to EXPLAIN WHY those exact scores and performance levels occurred using the measured metrics.\n"
    "4. If a metric is missing/unavailable, write strictly: 'Metric not available.'\n"
    "5. Do NOT use Markdown code blocks or markdown tables.\n"
    "6. Produce clean, professional, terminal-friendly text.\n"
    "7. Keep the tone encouraging, constructive, and HR-aligned."
)

REPORT_TEMPLATE: str = (
    "INTERVIEW TELEMETRY DATA:\n\n"
    "{telemetry}\n\n"
    "GENERATE REPORT USING THIS EXACT STRUCTURE:\n\n"
    "######################################################################\n"
    "                     HIREFLOW AI INTERVIEW REPORT\n"
    "######################################################################\n\n"
    "1. Overall Interview Summary\n"
    "Show:\n"
    "Overall Score: [overall_interview_score from JSON]\n"
    "Performance Level: [overall_performance_level from performance_classifications in JSON]\n"
    "Interview Readiness: [interview_readiness_level from performance_classifications in JSON]\n\n"
    "------------------------------------------------------------\n\n"
    "2. Executive Summary\n"
    "Write 6–10 lines explaining complete performance strictly referencing telemetry and performance_classifications.\n\n"
    "------------------------------------------------------------\n\n"
    "3. Performance Breakdown\n"
    "For each category (Confidence, Attention, Eye Contact, Emotion Stability, Head Stability):\n"
    "• Category Name:\n"
    "  - Score: [Value from JSON]\n"
    "  - Performance Level: [Exact pre-calculated label from performance_classifications in JSON]\n"
    "  - Explanation: [Explain WHY this level was obtained based on measured metrics]\n\n"
    "------------------------------------------------------------\n\n"
    "4. Eye Contact Analysis\n"
    "Use Eye Contact %, Eye Stability, and Gaze Direction.\n\n"
    "------------------------------------------------------------\n\n"
    "5. Attention Analysis\n"
    "Use Average Attention, Focus Time, Looking Away Time, and Distraction Events.\n\n"
    "------------------------------------------------------------\n\n"
    "6. Emotion Analysis\n"
    "Use Dominant Emotion, Emotion Stability, and Emotion Distribution.\n\n"
    "------------------------------------------------------------\n\n"
    "7. Stress Analysis\n"
    "Use Blink Count, Blink Rate, Eye Movement, and Attention.\n\n"
    "------------------------------------------------------------\n\n"
    "8. Head Pose Analysis\n"
    "Use Head Pose and Head Stability.\n\n"
    "------------------------------------------------------------\n\n"
    "9. Face Visibility Analysis\n"
    "Use Visibility %, Distance, and Face Position.\n\n"
    "------------------------------------------------------------\n\n"
    "10. Strengths\n"
    "List 4 strengths referencing telemetry.\n\n"
    "------------------------------------------------------------\n\n"
    "11. Areas for Improvement\n"
    "List 4 areas for improvement referencing telemetry.\n\n"
    "------------------------------------------------------------\n\n"
    "12. Action Plan\n"
    "Provide 5 practical recommendations explaining WHY and HOW.\n\n"
    "------------------------------------------------------------\n\n"
    "13. Interview Readiness\n"
    "State Level: [interview_readiness_level from performance_classifications]\n"
    "Reason: [Explain why based on overall telemetry]\n\n"
    "------------------------------------------------------------\n\n"
    "14. Recruiter Comments\n"
    "Provide positive observations first, then improvement areas in an encouraging tone.\n\n"
    "------------------------------------------------------------\n\n"
    "15. Final Verdict\n"
    "Summarize complete performance in one professional paragraph.\n\n"
    "End of report."
)


def generate_llm_feedback(session_report: Dict[str, Any]) -> str:
    """
    Sends raw telemetry and Python pre-calculated classifications to Ollama /api/chat endpoint.
    Streams structured report directly to output.
    """
    if not session_report or session_report.get("overall_interview_score") is None:
        error_msg = "Error: Invalid or empty telemetry data received."
        print(f"\n[Telemetry Validation Error]: {error_msg}")
        return error_msg

    telemetry_json_str: str = json.dumps(session_report, indent=2)
    user_message: str = REPORT_TEMPLATE.format(telemetry=telemetry_json_str)

    payload: Dict[str, Any] = {
        "model": MODEL_NAME,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message}
        ],
        "stream": True,
        "options": {
            "temperature": 0.0,
            "top_p": 0.9,
            "num_ctx": 8192,
            "num_predict": 2048
        }
    }

    full_response: str = ""
    try:
        with requests.post(OLLAMA_API_URL, json=payload, stream=True, timeout=600) as response:
            if response.status_code == 200:
                for line in response.iter_lines():
                    if not line:
                        continue

                    try:
                        chunk: Dict[str, Any] = json.loads(line.decode('utf-8'))
                    except json.JSONDecodeError:
                        continue

                    if "error" in chunk:
                        err_res = f"\nOllama Stream Error: {chunk['error']}"
                        print(err_res)
                        return err_res

                    content = chunk.get("message", {}).get("content")
                    if content:
                        print(content, end="", flush=True)
                        full_response += content

                    if chunk.get("done", False):
                        break

                print("\n")

                # Save combined telemetry and report log
                try:
                    with open("latest_report.txt", "w", encoding="utf-8") as f:
                        f.write("================ TELEMETRY INPUT ================\n\n")
                        f.write(telemetry_json_str)
                        f.write("\n\n================ GENERATED REPORT ================\n\n")
                        f.write(full_response)
                except IOError as e:
                    print(f"\n[Warning]: Failed to save report log: {e}")

                return full_response
            else:
                error_res = f"Ollama API Error ({response.status_code}): {response.text}"
                print(error_res)
                return error_res
    except Exception as e:
        error_res = f"Failed to connect to Ollama API: {str(e)}"
        print(error_res)
        return error_res